stages:
  - tests
  - build
  - deploy

format:
  image: rust:latest
  stage: tests
  before_script:
    - rustup component add rustfmt clippy
  script:
    - cargo fmt --check
    - cargo clippy

build:
  image: registry.gitlab.com/ytanimura/yotabaito/ci-container
  stage: build
  script:
    - trunk build
  artifacts:
    paths:
      - dist

pages:
  image: debian:latest
  stage: deploy
  script:
    - mv dist public
  artifacts:
    paths:
      - public
  only:
    - main
