[build]
target = "index.html"
dist = "dist"
public_url = "./"

[[hooks]]
stage = "pre_build"
command = "curl"
command_arguments = [
    # sdf font texture
    "https://raw.githubusercontent.com/otaviogood/shader_fontgen/master/codepage12.png",
    "-o",
    "./resources/codepage12.png",
]
